baseurl = "http://www.levcards.com/"
title = "LevCards"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-38157931-3"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Levcards - Crypto-art by Lev Polyakov"
  copyright = "<a href='/copyright'>&copy; 2018 Lev Polyakov</a>. All rights reserved."
  sidebarAbout = [
    "Lev is a creative illustrator and animation director.",
    "Originally from St. Petersburg, Russia, currently and forever based in New York."
  ]
  # Contact page
  email = "talk@levpolyakov.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/lev.polyakov"
  # email         = "talk@levpolyakov.com"
  twitter       = "https://twitter.com/levpo"
  linkedin      = "https://www.linkedin.com/in/levpolyakov/"
  instagram     = "https://www.instagram.com/levpolyakov/"
  youtube       = "https://www.youtube.com/channel/UCSEcUvChjYe_iwqvqVhuOAQ" 
  # github        = "https://github.com/levpolyakov"
  # googleplus    = "full profile url in googleplus"
  # stackoverflow = "full profile url in stackoverflow"

[taxonomies]
  tag = "tags"
