[build]
publish = "public"
command = "hugo"

[context.deploy-preview]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.42"

[context.deploy-preview.environment]
HUGO_VERSION = "0.42"
